iversion: 2
jobs:
  build:
    docker:
      - image: base/archlinux
    steps:
      - checkout
      - run:
          name: Update
          command: pacman -Syu --noconfirm
      - run:
          name: Install
          command: pacman -S clang --noconfirm
      - run:
          name: Install
          command: pacman -S make --noconfirm
      - run:
          name: make lib
          command: make
      - run: 
          name: flash LD_LIBRARY_PATH
          command: LD_LIBRARY_PATH=$PWD/lib:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH
      - run:
          name: run test 
          command: make test
      - run:
          name: run example
          command: ./a.out

