iversion: 2
jobs:
  build:
    docker:
      - image: base/archlinux
    steps:
      - checkout
      - run:
          name: Update
          command: pacman -Syu --noconfirm
      - run:
          name: Install
          command: pacman -S clang --noconfirm
      - run:
          name: make lib
          command: make
      - run:
          name: Print the Current Time
          command: date

